Include headless mode
weechat/weechat-container pull request #2
Opened 2022-08-08 08:22 UTC by hamishfagg

Compile with headless mode enabled for people who are just using weechat as a headless relay. (zstd-libs was also missing from the alpine images).

2022-08-09 21:44 UTC, flashcode requested changes
Hi,

Thanks for the pull request!

I made some comments, and I have a last one: you could update the target "test_container" in the Makefile to also test the weechat-headless binary (by asking the version, like for the weechat command).
So we are sure the command is also properly installed in the built container.

2022-08-09 21:44 UTC, flashcode commented on alpine/Containerfile
> +	          -DENABLE_HEADLESS=ON \
Please replace the Tab by spaces.

2022-08-09 21:44 UTC, flashcode commented on alpine/Containerfile
> +	          -DENABLE_HEADLESS=ON \
You should also enable headless when building slim container (in the else below).

2022-08-09 21:44 UTC, flashcode commented on alpine/Containerfile
> +	      zstd-libs \
Please replace the Tab by spaces.

2022-08-09 21:44 UTC, flashcode commented on debian/Containerfile
> +	          -DENABLE_HEADLESS=ON \
Please replace the Tab by spaces.

2022-08-09 21:44 UTC, flashcode commented on debian/Containerfile
> +	          -DENABLE_HEADLESS=ON \
You should also enable headless when building slim container (in the else below).

2022-08-24 08:13 UTC, hamishfagg commented
Implemented those changes. Sorry it took so long 😛

2022-09-01 18:35 UTC, flashcode commented
Thanks, merged (with extra fix on missing Tab in Makefile).

2022-09-01 18:35 UTC, closed without merging